name: tensorflow-mac
channels:
  - apple
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - hdf5=1.12.1
  - krb5=1.21.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libcxx=19.1.7
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnghttp2=1.58.0
  - libopenblas=0.3.28
  - libprotobuf=3.19.6
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libzlib=1.2.13
  - llvm-openmp=19.1.7
  - ncurses=6.5
  - openssl=3.4.0
  - pip=25.0
  - python=3.10.14
  - python_abi=3.10
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - tensorflow-deps=2.10.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - cachetools==5.5.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.17.0
      - flatbuffers==25.1.24
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - gast==0.4.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - h5py==3.12.1
      - idna==3.10
      - imbalanced-learn==0.11.0
      - imblearn==0.0
      - jinja2==3.1.5
      - joblib==1.4.2
      - keras==2.13.1
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.7.2
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.4.2
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.14.0
      - packaging==24.2
      - pandas==2.0.3
      - pathlib==1.0.1
      - pathtools==0.1.2
      - pillow==10.0.0
      - protobuf==3.20.3
      - psutil==6.1.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pygments==2.19.1
      - pyparsing==3.0.9
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.9.4
      - rsa==4.9
      - scikit-learn==1.3.0
      - scipy==1.15.1
      - seaborn==0.13.2
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - smmap==5.0.2
      - sns==0.1
      - sympy==1.13.1
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.13.0
      - tensorflow-metal==1.0.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wandb==0.15.9
      - werkzeug==3.1.3
      - wrapt==1.17.2
